name: Check PR Title

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull-requests: write
    steps:
      - name: Check that PR title follows semantic commit specification
        uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Inform about diverging PR title naming
        uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fail, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there! 👋

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
            Examples of valid PR titles:

            - feat: support new error codes
            - fix(config): correct env resolution
            - ci: add new workflow for linting

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - name: Delete a comment if the issue resolved
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        with:
          header: pr-title-lint-error
          delete: true
